#POST http://localhost:8080/users/login
POST http://localhost:12040/users/login
Content-Type: application/json

{
  "id": "seungkyu",
  "password": "1204"
}

> {%
 client.test("test", function(){
     client.assert(response.status == 200)
     client.global.set("token", response.body.token)
 })
 %}