POST http://localhost:8080/users/register
#POST http://localhost:12040/users/register
Content-Type: application/json

{
  "user_id": "seungkyu",
  "password": "1204",
  "nickname": "seungkyu"
}

> {%
client.test("register", function(){
    client.assert(response.status == 201)
})
 %}