GET http://localhost:8081/posts/find?name=test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InNldW5na3l1Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3MzAxMjA4MjQsImV4cCI6MTczMDEyODAyNH0.eKVFBRw5TcXBfhUN2Y3hCrOJCLEH11kk3bqEkH7fQY4