server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://seungkyu:1204@mongodb:27017/users?authSource=admin
      auto-index-creation: false
    redis:
      host: localhost
      port: 12042

jwt:
  secret-key: newSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyunewSeungkyu