server:
  port: 12040

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
        - id: post
          uri: http://localhost:8081
          predicates:
            - Path=/posts/**
  main:
    web-application-type: reactive